# Generated by Django 5.1.6 on 2025-04-07 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaperfil',
            name='respuesta',
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='talentracker.preguntaperfil')),
            ],
        ),
        migrations.AddField(
            model_name='respuestaperfil',
            name='opcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talentracker.opcionpregunta'),
        ),
    ]
