# Generated by Django 5.1.6 on 2025-03-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculos/'),
        ),
    ]
