# Generated by Django 5.1.6 on 2025-04-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentracker', '0002_remove_respuestaperfil_respuesta_opcionpregunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('empleado', 'Empleado'), ('empresa', 'Empresa')], default='empleado', max_length=10),
        ),
    ]
