# Generated by Django 5.1.6 on 2025-04-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentracker', '0006_configuracionnotificaciones_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertatrabajo',
            name='habilidades',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ofertatrabajo',
            name='industria',
            field=models.CharField(choices=[('tecnologia', 'Tecnología'), ('salud', 'Salud'), ('finanzas', 'Finanzas'), ('educacion', 'Educación'), ('servicios', 'Servicios'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
        migrations.AddField(
            model_name='ofertatrabajo',
            name='nivel_academico',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('secundaria', 'Secundaria'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('posgrado', 'Posgrado')], default='ninguno', max_length=20),
        ),
        migrations.AddField(
            model_name='ofertatrabajo',
            name='nivel_experiencia',
            field=models.CharField(choices=[('junior', 'Junior'), ('intermedio', 'Intermedio'), ('senior', 'Senior')], default='junior', max_length=20),
        ),
        migrations.AddField(
            model_name='ofertatrabajo',
            name='remoto',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('mixto', 'Mixto')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='ofertatrabajo',
            name='salario_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ofertatrabajo',
            name='ubicacion',
            field=models.CharField(default='No especificada', max_length=100),
        ),
    ]
