# Generated by Django 5.1.6 on 2025-05-08 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentracker', '0007_ofertatrabajo_habilidades_ofertatrabajo_industria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name': 'Like a oferta', 'verbose_name_plural': 'Likes a ofertas'},
        ),
        migrations.AlterUniqueTogether(
            name='notificacion',
            unique_together={('usuario', 'oferta')},
        ),
        migrations.CreateModel(
            name='LikeOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentracker.ofertatrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
