# Generated by Django 5.1.6 on 2025-05-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talentracker', '0008_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likeoferta',
            options={'verbose_name': 'Like a oferta', 'verbose_name_plural': 'Likes a ofertas'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterUniqueTogether(
            name='notificacion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='likeoferta',
            unique_together={('usuario', 'oferta')},
        ),
    ]
