# Generated by Django 5.1.6 on 2025-05-22 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentracker', '0009_alter_likeoferta_options_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel_experiencia', models.CharField(blank=True, choices=[('junior', 'Junior'), ('intermedio', 'Intermedio'), ('senior', 'Senior')], max_length=20, null=True)),
                ('industria', models.CharField(blank=True, choices=[('tecnologia', 'Tecnología'), ('salud', 'Salud'), ('finanzas', 'Finanzas'), ('educacion', 'Educación'), ('servicios', 'Servicios'), ('otros', 'Otros')], max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('remoto', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('mixto', 'Mixto')], max_length=10, null=True)),
                ('nivel_academico', models.CharField(blank=True, choices=[('ninguno', 'Ninguno'), ('secundaria', 'Secundaria'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('posgrado', 'Posgrado')], max_length=20, null=True)),
                ('habilidades', models.JSONField(blank=True, default=list)),
                ('predeterminado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_busqueda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de búsqueda',
                'verbose_name_plural': 'Preferencias de búsqueda',
            },
        ),
    ]
