# Generated by Django 5.1.6 on 2025-05-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentracker', '0011_usuario_biografia_usuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertatrabajo',
            name='remoto',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20),
        ),
        migrations.AlterField(
            model_name='preferenciabusqueda',
            name='remoto',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=20, null=True),
        ),
    ]
