# Generated by Django 5.1.6 on 2025-05-22 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentracker', '0012_alter_ofertatrabajo_remoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_inicio', models.DateTimeField(auto_now_add=True)),
                ('duracion_segundos', models.IntegerField(default=0)),
                ('interaccion_completa', models.BooleanField(default=False)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentracker.ofertatrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vista de oferta',
                'verbose_name_plural': 'Vistas de ofertas',
            },
        ),
    ]
