# Generated by Django 5.1.6 on 2025-05-23 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentracker', '0013_vistaoferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidades', models.JSONField(default=list)),
                ('nivel_experiencia', models.CharField(choices=[('junior', 'Junior'), ('intermedio', 'Intermedio'), ('senior', 'Senior')], default='junior', max_length=20)),
                ('ubicacion', models.CharField(default='No especificada', max_length=100)),
                ('preferencia_modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('mixto', 'Mixto')], default='presencial', max_length=20)),
                ('nivel_academico', models.CharField(choices=[('ninguno', 'Ninguno'), ('secundaria', 'Secundaria'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('posgrado', 'Posgrado')], default='ninguno', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
