from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('elegir-tipo/', views.elegir_tipo_usuario, name='elegir_tipo'),
    path('registro/empleado/', views.registro_empleado, name='registro_empleado'),
    path('registro/empresa/', views.registro_empresa, name='registro_empresa'),
    path('iniciar-sesion/', views.iniciar_sesion, name='iniciar_sesion'),
    path('cerrar-sesion/', views.cerrar_sesion, name='cerrar_sesion'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/empresa/', views.dashboard_empresa, name='dashboard_empresa'),
    path('ofertas/crear/', views.crear_oferta, name='crear_oferta'),
    path('ofertas/editar/<int:oferta_id>/', views.editar_oferta, name='editar_oferta'),
    path('ofertas/eliminar/<int:oferta_id>/', views.eliminar_oferta, name='eliminar_oferta'),
    path('ofertas/postular/<int:oferta_id>/', views.postular, name='postular'),
    path('ofertas/like/<int:oferta_id>/', views.toggle_like, name='toggle_like'),
    path('ofertas/empresa/', views.ver_ofertas_empresa, name='ver_ofertas_empresa'),
    path('favoritos/', views.favoritos, name='favoritos'),
    path('perfil/empleado/', views.ver_perfil_empleado, name='ver_perfil_empleado'),
    path('perfil/empleado/editar/', views.editar_perfil_empleado, name='editar_perfil_empleado'),
    path('perfil/profesional/editar/', views.editar_perfil_profesional, name='editar_perfil_profesional'),
    path('notificaciones/configurar/', views.configurar_notificaciones, name='configurar_notificaciones'),
    path('notificaciones/', views.ver_notificaciones, name='ver_notificaciones'),
    path('notificaciones/marcar-leida/<int:notificacion_id>/', views.marcar_leida, name='marcar_leida'),
    path('recomendaciones/', views.obtener_recomendaciones, name='obtener_recomendaciones'),
    path('preferencias/', views.preferencias_busqueda, name='preferencias_busqueda'),
    path('preferencias/editar/<int:preferencia_id>/', views.editar_preferencia, name='editar_preferencia'),
    path('preferencias/eliminar/<int:preferencia_id>/', views.eliminar_preferencia, name='eliminar_preferencia'),
    path('preferencias/aplicar/<int:preferencia_id>/', views.aplicar_preferencia, name='aplicar_preferencia'),
    path('reporte/', views.generar_reporte, name='generar_reporte'),
    path('reporte/pdf/', views.descargar_reporte_pdf, name='descargar_reporte_pdf'),
    path('ofertas/vista/iniciar/<int:oferta_id>/', views.iniciar_vista_oferta, name='iniciar_vista_oferta'),
    path('ofertas/vista/finalizar/<int:vista_id>/', views.finalizar_vista_oferta, name='finalizar_vista_oferta'),
    path('postulante/<int:oferta_id>/<int:usuario_id>/', views.ver_detalle_postulante, name='ver_detalle_postulante'),
] 